### ISSUE TITLE
Frequent slowdowns

### ISSUE THREAD

**Issue by IPWright83** [mantoni/eslint_d.js#202]
I'm using `eslint_d` through a Sublime extension to auto format https://github.com/TheSavior/ESLint-Formatter and I'm seeing frequently that Sublime reports that it's become unresponsive, only when using said extension.

I've tried running `eslint_d` via the command line and noticed that while it's often quick, sometimes it runs as though it's just warming up for the first time, and therefore takes 30s+ (unfortunately in my project :( ). This is when I've been saving the same file multiple times so it should have already been cached.

Is there anyway I can debug/find out more information as to why I'm hitting these frequent slow-downs on files that should be cached? I've seen there's `eslint_d status`, but it doesn't tell me a huge amount, and running before every file save is going to be awkward :/

**Comment by IPWright83** [comment]
Potentially related, I've noticed that as I pull out tabs from Sublime into new windows it seems to create a new `eslint_d` instance for each, and the extension I'm using never closes them down.

> ❯ eslint_d status
Running. 2 instances cached.

I managed to get a reproduction when creating a 2nd instance. I'm not sure if this is `eslint_d` at fault or the extension I'm using though.

![eslint_d](https://user-images.githubusercontent.com/1374775/173809545-81e45f02-b8a2-42de-8b87-e105629fe8d6.gif)

**Comment by IPWright83** [comment]
Thought I should share my config:

```
"node_path": {
        "linux": "/home/ian/.nvm/versions/node/v16.14.0/bin/node"
    },
    "local_eslint_path": {
        "linux": "/home/ian/.nvm/versions/node/v16.14.0/bin/eslint_d"
    }
```

I'm wondering if installing `eslint_d` locally to my project may help with this?

**Comment by IPWright83** [comment]
Yeah, I suspected that might be the case when I saw https://github.com/TheSavior/ESLint-Formatter/blob/master/ESLint-Formatter.py#L73 but I tried logging the commands used and I couldn't see the `cwd` being passed in anywhere.

That being said, I noticed that the fix results were also different, the window'd version was fixing to I'm guessing the default set of rules, where-as the project was fixing to the `.eslintrc` config which was subtly different.

The plugin I'm using doesn't seem to get much attention at the moment, so I'm currently trying to work out ways I can debug & potentially resolve this. I'm guessing if I were to use `--resolve-plugins-relative-to` and hard-code to my `cwd` then I'd only ever have 1 instance of `eslint_d`? Problem is I'd only then be able to run it for a single project :/

**Comment by IPWright83** [comment]
I've confirmed that this comes down to the `cwd`. When this is working correctly the `cwd` is the top level directory of my project, where-as when it's broken in a separate window it's treating the `cwd` as the directory in which the file lives in.

I've been mulling over how I could fix this, and I reckon walking back up the directory structure until a `package.json` is found, then treating that as the `cwd` would fix my issue. Would you be open to considering that? Possibly with a new CLI switch to select that behaviour to ensure this is non-breaking for existing users?

**Comment by IPWright83** [comment]
I reckon something like this would work - just not 100% sure where the best place to put it is?

```
const fs = require('fs');
const path = require('path');

function findPackageJsonDir(currentDir) {
    const containsPackageJson =
        fs.readdirSync(currentDir).filter((f) => f.includes('package.json')).length > 0;

    if (containsPackageJson) {
        return currentDir;
    }

    // Check for hitting the root without finding a package.json
    const parent = path.dirname(currentDir);
    if (parent === currentDir) {
        return null;
    }

    return findPackageJsonDir(path.dirname(currentDir));
}
```

**Comment by mantoni** [comment]
I'm open to your suggestions. I wonder how eslint itself handles this. Ideally eslint_d behaves the same, or even uses eslint APIs to find the cwd. If that's possible, I wouldn't even put it behind a flag. If eslint_d behavior behaves potentially different from eslint, I think it should be behind a flag.

**Comment by mantoni** [comment]
Another idea: How about checking if the current cwd is a sub-directory of one of the cached instances?

**Comment by IPWright83** [comment]
That'd work well - probably an easier change to make too?

**Comment by mantoni** [comment]
Easy to implement, and also a synchronous check without additional IO.

I'm a little worried though. This might cause issues if an instance is cached in my home directory and all of the project folders would then use that instance 🤔

**Comment by mantoni** [comment]
In any case, the place to look at in the code is `lib/caches.js` in the `getCache` function.

You could implement some sort of "project root path resolution" there, behind a flag.

**Comment by IPWright83** [comment]
> Easy to implement, and also a synchronous check without additional IO.
> 
> I'm a little worried though. This might cause issues if an instance is cached in my home directory and all of the project folders would then use that instance thinking

That's true - but I guess an easy workaround? `eslint_d stop` then re run in the correct project folder? Then you've set up a new set of caching.

**Comment by mantoni** [comment]
I thought some more about it and it could also cause unexpected behavior in mono-repo project setups.

I'm okay with supporting a new command line flag for project root resolution. This will fix it for you and doesn't change the caching behavior for anyone else.

**Comment by IPWright83** [comment]
So I've discovered you can set the working directory externally when launching `eslint_d` as used by another plugin. I feel like this might be a cleaner approach, and not require any changes to `eslint_d` so I'm going to try that approach first.

**Comment by mantoni** [comment]
Maybe this is also interesting for you: https://github.com/mantoni/eslint_d.js/issues/203

**Comment by IPWright83** [comment]
@mantoni that looks like a similar problem to the one I hit. The problem is the path to the `project/node_modules/eslint_d` is fixed for each project, but this is a global setting for the plug-in. I tried to fix it in a slightly more generic way using the same approach we were going to do with `eslint_d` but pushed it into the plugin instead.

https://github.com/TheSavior/ESLint-Formatter/pull/90

**Comment by mantoni** [comment]
I guess this can be closed as resolved now, right? Thank you for all the work ❤️

**Comment by IPWright83** [comment]
Yeah, thanks @mantoni . I still get issues for new files unfortunately that haven't been cached yet which there's not much can be done. But I think the other problems are now gone.

**Comment by mantoni** [comment]
Thanks for the feedback. If you have ideas how to further improve the situation, feel free to open a new issue.
